version: 2.1
jobs:
  node:
    working_directory: ~/navi-capacitor
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run: yarn install
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run: yarn build && yarn setup && yarn sync
      - persist_to_workspace:
          root: ~/navi-capacitor
          paths:
            - android
            - node_modules

  macos-build:
    working_directory: ~/navi-capacitor/ios/App
    macos:
      xcode: 11.3.0
    steps:
      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - restore_cache:
          key: pods-v1-{{ checksum "Podfile.lock" }}-{{ arch }}
      - run: pod install
      - run: bundle install
      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - save_cache:
          key: pods-v1-{{ checksum "Podfile.lock" }}-{{ arch }}
          paths:
            - ios/Pods
      - run:
          name: Fastlane
          command: fastlane build
          working_directory: ios
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  android-build:
    working_directory: ~/navi-capacitor/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/navi-capacitor
      - attach_workspace:
          at: ~/navi-capacitor
      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run: bundle install
      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - run:
          name: build apk
          command: ./gradlew clean assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/
      - run:
          name: import KEYSTORE of environment variable
          command: echo "$ANDROID_PRODUCTION_KEYSTORE" | base64 -di > app/production.keystore
      - run:
          name: assign apk and build in fastlane
          command: fastlane deploy

workflows:
  node-android:
    jobs:
      - node
      - android-build:
          requires:
            - node
      - macos-build:
          requires:
            - node
